const zodiac = [
    {
        "id": 1,
        "name": "Aries",
        "description": "",
        "longitude_start": "0",
        "longitude_end": "30",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Aries.svg",
        "unicode_symbol": "♈",
        "gloss": "The Ram",
        "element": "Fire",
        "ruling_body_classic": "Mars",
        "ruling_body_modern": "Mars",
        "quality": "Cardinal",
        "start": "21/03",
        "end": "20/04",
    },
    {
        "id": 2,
        "name": "Taurus",
        "description": '',
        "longitude_start": "30",
        "longitude_end": "60",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Taurus.svg",
        "unicode_symbol": "♉",
        "gloss": "The Bull",
        "element": "Earth",
        "ruling_body_classic": "Venus",
        "ruling_body_modern": "Earth",
        "quality": "Fixed",
        "start": "21/04",
        "end": "20/05",
    },
    {
        "id": 3,
        "name": "Gemini",
        "description": "",
        "longitude_start": "60",
        "longitude_end": "90",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Gemini.svg",
        "unicode_symbol": "♊",
        "gloss": "The Twins",
        "element": "Air",
        "ruling_body_classic": "Mercury",
        "ruling_body_modern": "Mercury",
        "quality": "Mutable",
        "start": "21/05",
        "end": "20/06",
    },
    {
        "id": 4,
        "name" : "Cancer",
        "description": "",
        "longitude_start": "90",
        "longitude_end": "120",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Cancer.svg",
        "unicode_symbol": "♋",
        "gloss": "The Crab",
        "element": "Water",
        "ruling_body_classic": "Moon",
        "ruling_body_modern": "Moon",
        "quality": "Cardinal",
        "start": "21/06",
        "end": "21/07",
    },
    {
        "id": 5,
        "name": "Leo",
        "description": "",
        "longitude_start": "120",
        "longitude_end": "150",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Leo.svg",
        "unicode_symbol": "♌",
        "gloss": "The Lion",
        "element": "Fire",
        "ruling_body_classic": "Sun",
        "ruling_body_modern": "Sun",
        "quality": "Fixed",
        "start": "22/07",
        "end": "21/08",
    },
    {
        "id": 6,
        "name" : "Virgo",
        "description": "",
        "longitude_start": "150",
        "longitude_end": "180",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Virgo.svg",
        "unicode_symbol": "♍",
        "gloss": "The Virgin",
        "element": "Earth",
        "ruling_body_classic": "Mercury",
        "ruling_body_modern": "Ceres",
        "quality": "Mutable",
        "start": "22/08",
        "end": "21/09",
    },
    {
        "id": 7,
        "name": "Libra",
        "description": "",
        "longitude_start": "180",
        "longitude_end": "210",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Libra.svg",
        "unicode_symbol": "♎",
        "gloss": "The Scales",
        "element": "Air",
        "ruling_body_classic": "Venus",
        "ruling_body_modern": "Venus",
        "quality": "Cardinal",
        "start": "22/09",
        "end": "21/10",
    },
    {
        "id": 8,
        "name": "Scorpio",
        "description": "",
        "longitude_start": "210",
        "longitude_end": "240",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Scorpio.svg",
        "unicode_symbol": "♏",
        "gloss": "The Scorpion",
        "element": "Water",
        "ruling_body_classic": "Mars",
        "ruling_body_modern": "Pluto",
        "quality": "Fixed",
        "start": "22/10",
        "end": "21/11",
    },
    {
        "id": 9,
        "name": "Sagittarius",
        "description": "",
        "longitude_start": "240",
        "longitude_end": "270",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Sagittarius.svg",
        "unicode_symbol": "♐",
        "gloss": "The Archer",
        "element": "Fire",
        "ruling_body_classic": "Jupiter",
        "ruling_body_modern": "Jupiter",
        "quality": "Mutable",
        "start": "22/11",
        "end": "21/12",
    },
    {
        "id": 10,
        "name" : 'Capricorn',
        "description": "",
        "longitude_start": "270",
        "longitude_end": "300",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Capricorn.svg",
        "unicode_symbol": "♑",
        "gloss": "The Mountain Sea-Goat",
        "element": "Earth",
        "ruling_body_classic": "Saturn",
        "ruling_body_modern": "Saturn",
        "quality": "Cardinal",
        "start": "22/12",
        "end": "20/01",
    },
    {
        "id": 11,
        "name" : "Aquarius",
        "description": "",
        "longitude_start": "300",
        "longitude_end": "330",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Aquarius.svg",
        "unicode_symbol": "♒",
        "gloss": "The Water Bearer",
        "element": "Air",
        "ruling_body_classic": "Saturn",
        "ruling_body_modern": "Uranus",
        "quality": "Fixed",
        "start": "21/01",
        "end": "19/02",
    },
    {
        "id": 12,
        "name" : "Pisces",
        "description": "",
        "longitude_start": "330",
        "longitude_end": "360",
        "svg_symbol": "https://en.wikipedia.org/wiki/File:Pisces.svg",
        "unicode_symbol": "♓",
        "gloss": "The Fish",
        "element": "Water",
        "ruling_body_classic": "Jupiter",
        "ruling_body_modern": "Neptune",
        "quality": "Mutable",
        "start": "20/02",
        "end": "20/03",

    },
];

export default zodiac;