const scores = [
    {
        "id": 1,
        "score": 1,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 2,
        "score": 2,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 3,
        "score": 3,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 4,
        "score": 4,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 5,
        "score": 5,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 6,
        "score": 6,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 7,
        "score": 7,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 8,
        "score": 8,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 9,
        "score": 9,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 10,
        "score": 10,
        "ashakoot": 0,
        "dahakoot": 0,
    },
    {
        "id": 11,
        "score": 11,
        "ashakoot": 1,
        "dahakoot": 1,
    },
    {
        "id": 12,
        "score": 12,
        "ashakoot": 2,
        "dahakoot": 2,
    },
    {
        "id": 13,
        "score": 13,
        "ashakoot": 3,
        "dahakoot": 3,
    },
    {
        "id": 14,
        "score": 14,
        "ashakoot": 4,
        "dahakoot": 4,
    },
    {
        "id": 15,
        "score": 15,
        "ashakoot": 5,
        "dahakoot": 5,
    },
    {
        "id": 16,
        "score": 16,
        "ashakoot": 6,
        "dahakoot": 6,
    },
    {
        "id": 17,
        "score": 17,
        "ashakoot": 7,
        "dahakoot": 7,
    },
    {
        "id": 18,
        "score": 18,
        "ashakoot": 13,
        "dahakoot": 13,
    },
    {
        "id": 19,
        "score": 19,
        "ashakoot": 14,
        "dahakoot": 14,
    },
    {
        "id": 20,
        "score": 20,
        "ashakoot": 14,
        "dahakoot": 14,
    },
    {
        "id": 21,
        "score": 21,
        "ashakoot": 15,
        "dahakoot": 15,
    },
    {
        "id": 22,
        "score": 22,
        "ashakoot": 15,
        "dahakoot": 15,
    },
    {
        "id": 23,
        "score": 23,
        "ashakoot": 16,
        "dahakoot": 16,
    },
    {
        "id": 24,
        "score": 24,
        "ashakoot": 17,
        "dahakoot": 17,
    },
    {
        "id": 25,
        "score": 25,
        "ashakoot": 17,
        "dahakoot": 17,
    },
    {
        "id": 26,
        "score": 26,
        "ashakoot": 18,
        "dahakoot": 18,
    },
    {
        "id": 27,
        "score": 27,
        "ashakoot": 18,
        "dahakoot": 18,
    },
    {
        "id": 28,
        "score": 28,
        "ashakoot": 19,
        "dahakoot": 19,
    },
    {
        "id": 29,
        "score": 29,
        "ashakoot": 19,
        "dahakoot": 19,
    },
    {
        "id": 30,
        "score": 30,
        "ashakoot": 19,
        "dahakoot": 19,
    },
    {
        "id": 31,
        "score": 31,
        "ashakoot": 19,
        "dahakoot": 19,
    },
    {
        "id": 32,
        "score": 32,
        "ashakoot": 20,
        "dahakoot": 20,
    },
    {
        "id": 33,
        "score": 33,
        "ashakoot": 20,
        "dahakoot": 20,
    },
    {
        "id": 34,
        "score": 34,
        "ashakoot": 20,
        "dahakoot": 20,
    },
    {
        "id": 35,
        "score": 35,
        "ashakoot": 20,
        "dahakoot": 20,
    },
    {
        "id": 36,
        "score": 36,
        "ashakoot": 20,
        "dahakoot": 20,
    },
];

export default scores;